// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OSI3RvmOa_qyMSU8QO1vXAldB0RoHc4',
    appId: '1:826217552364:android:25d46316de02310f02c8c9',
    messagingSenderId: '826217552364',
    projectId: 'favorite-live-rkskap',
    databaseURL: 'https://favorite-live-rkskap-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'favorite-live-rkskap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgPauziusiX_mcEHAS71WknnYx-wvOAU',
    appId: '1:826217552364:ios:4a80bb80fb1a6d6602c8c9',
    messagingSenderId: '826217552364',
    projectId: 'favorite-live-rkskap',
    databaseURL: 'https://favorite-live-rkskap-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'favorite-live-rkskap.appspot.com',
    androidClientId: '826217552364-13703ffb63jj6mpe81kpk1bl5qf56aro.apps.googleusercontent.com',
    iosClientId: '826217552364-f7siooo9c9913660bht1im7ktlfhh732.apps.googleusercontent.com',
    iosBundleId: 'com.example.favouriteApplication',
  );
}
